[build]
  command = "npm run build"
  publish = "dist"

# Ensure the correct Node.js version
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Custom build plugin for debugging
[[plugins]]
  package = "./build-plugin.js"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 